// 캔버스
var canvas = document.getElementById("body_box");
var ctx = canvas.getContext("2d");

// var img = new Image();
// img.src = "./image/background.png";

// img.onload = function(){
//     ctx.drawImage(img, 0, 0);
// }




// // 플레이어
// var player = {
//     x: 300,
//     y: 400,
//     size: 30,
//     speed: 5
// };

// // 키 입력
// var keys = {};

// // 별 공격
// var stars = [];


// // 시작
// function loaded(){

//     canvas = document.getElementById("body_box");
//     ctx = canvas.getContext("2d");

//     document.addEventListener("keydown", keyDown);
//     document.addEventListener("keyup", keyUp);

//     setInterval(gameLoop, 1000/60);
// }

// 집에서 작업 시작 전:

// git pull